### ISSUE TITLE
Latest changes v5.1.0 should be put on hold as they are not approved as per due proceedures

### ISSUE THREAD

**Issue by umesh-qs** [erasmus-without-paper/ewp-specs-api-discovery#15]
As per the discussion under https://github.com/erasmus-without-paper/ewp-specs-api-omobility-las/issues/35 latest changes should be put on hold and status should be changed to hold from released.

**Comment by janinamincer-daszkiewicz** [comment]
If I am not mistaken this issue is resolved in Discovery 6.0.0.
