### ISSUE TITLE
What is the point of having unique endpoint for General Purpose APIs?

### ISSUE THREAD

**Issue by umesh-qs** [erasmus-without-paper/ewp-specs-api-discovery#16]
As per new manifest changes, unique endpoint are mandatory for all the APIs. But why complicate this for "General Purpose APIs"
and Echo API?

**Comment by umesh-qs** [comment]
Also unique end point was a necessity for CNR APIs. That could have been handled by additional parameter only for CNR APIs.
Why are we opting for more work to change all the API urls to be unique.

**Comment by mkurzydlowski** [comment]
By introducing the requirement of unique APIs we are trying to simplify things not complicate them. It is all about enforcing 1-1 communication on a global level in EWP. Such communication doesn't require the requester to specify additional parameters in the request to indicate the HEI being called.

By doing this globally we aim to simplify the overall design of EWP APIs. But as there are already multiple APIs this means that this process will be gradual. Some parameters might be removed in the future as they will be unnecessary. It seems best to do it on occasion of major changes to an API.

As this is a change to the current EWP design you might see it as a complication, if you declared the same URL for different HEIs, but it shouldn't be an obstacle for anyone.

I wouldn't differentiate between APIs in this matter as that would make the design hard to understand. Every API that has to identify the HEI being called should use a unique URL. I believe that this means that even the General Purpose APIs and Echo API should be taken into account.

**Comment by georgschermann** [comment]
where is the (proposed) spec for the unique Endpoint URLs, didn't find it now

**Comment by janinamincer-daszkiewicz** [comment]
Look into last slides of  (deleted)
I gathered all relevant links there.

**Comment by georgschermann** [comment]
thanks, I found the link in another issue: 
https://owncloud.erasmuswithoutpaper.eu/index.php/s/zyNXSfU78NMtULf?path=%2F2022-04-06_Infrastructure_Forum#pdfviewer
yours seems to require login

**Comment by janinamincer-daszkiewicz** [comment]
Sorry, I forget that I use another path, than the one, which is publicly available. Link to public catalog is: https://owncloud.erasmuswithoutpaper.eu/index.php/apps/files/?dir=%2FESCI.
This is in the prsesentation about the Manifest files.

**Comment by janinamincer-daszkiewicz** [comment]
Is Michał's answer sufficient? If yes, I will close this issue.

**Comment by umesh-qs** [comment]
Yes. Thanks
