### ISSUE TITLE
Adding information about host provider to the manifest

### ISSUE THREAD

**Issue by mkurzydlowski** [erasmus-without-paper/ewp-specs-api-discovery#19]
During the Infrastructure Forum on 2022-03-02, it has been suggested to add information about the host provider to the manifest:

https://owncloud.erasmuswithoutpaper.eu/index.php/s/zyNXSfU78NMtULf?path=%2F2022-03-02_Infrastructure_Forum

Slide 21 contains the following bullet:
> Add information about provider to the first line of admin-notes:
`<ewp:admin-notes>Provider: MUCI (USOS)</ewp:admin-notes>`
`<ewp:admin-notes>Provider: Gent University (OASIS)</ewp:admin-notes>`
`<ewp:admin-notes>Provider: Masaryk University (ISOIS)</ewp:admin-notes>`

This recommendation has been well received by many partners and already implemented by some of them.

After that meeting another proposal has been made to move the provider name to a separate field in the manifest.

**Comment by mkurzydlowski** [comment]
This topic has also been discussed in those GitHub issues:
https://github.com/erasmus-without-paper/general-issues/issues/35#issuecomment-1073072243
https://github.com/erasmus-without-paper/ewp-specs-api-registry/issues/7#issuecomment-1073275467

**Comment by mkurzydlowski** [comment]
It should be noted that adding a new element to the EWP catalogue is backward-compatible as only the EWP registry implements the Registry API (see bullet two of the [backward-compatibility rules](https://github.com/erasmus-without-paper/ewp-specs-architecture#backward-compatibility-rules)).

That way, we don't need to force all of the EWP clients to change.

**Comment by janinamincer-daszkiewicz** [comment]
Just for reference, here it has been suggested to use a separate field:
https://github.com/erasmus-without-paper/ewp-specs-api-registry/issues/7#issuecomment-1081572458

> It should be noted that adding a new element to the EWP catalogue is backward-compatible as only the EWP registry implements the Registry API (see bullet two of the [backward-compatibility rules](https://github.com/erasmus-without-paper/ewp-specs-architecture#backward-compatibility-rules)). That way, we don't need to force all of the EWP clients to change.

Please, share your opinion

**Comment by georgschermann** [comment]
we added it in in the admin notes for now

**Comment by janinamincer-daszkiewicz** [comment]
Yes, some of the providers answered to my 'good practices' advice :)
However if we are to make the field mandatory, the separate field seems to be more appropriate.

**Comment by mkurzydlowski** [comment]
It has been voted to add a separate field for the provider name.

**Comment by janinamincer-daszkiewicz** [comment]
Done (Compare ewp-specs-api-discovery stable-v5 with stable-v6).
