### ISSUE TITLE
Allow for multiple EWP Hosts per manifest

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-api-discovery#7]
@mikesteez wrote:

> each individual HEI in the manifest will have to implement all APIs specified. For Sweden this will be the default case, but is it applicable to all countries? 

If I understood you correctly, you're asking about the following scenario:
- EWP Host `H` covers institution `HEI 1` and `HEI 2`, and it implements `API 1` for both institutions and `API 2` for just `HEI 1` (but not `HEI 2`). How to express it in the manifest file?

**Comment by wrygiel** [comment]
Currently, it is not possible to express it in a single manifest file. It _is_ possible to express it with two separate manifest files though. In the most extreme case, you would have a separate manifest for each of your APIs (or each of your institutions).

Adding direct references to all such additional manifests would be cumbersome however. I believe we can introduce a new `<include>` element to the manifest files. The registry would find such references and parse all the manifest files referenced.

What do you think?

**Comment by wrygiel** [comment]
> but is it applicable to all countries?

BTW, in Poland each HEI will be serving its own manifest file, and all the APIs will be hosted on HEI's servers. So, each HEI will be individually able to "switch EWP on", and all proper APIs will become available. My guess is that some APIs (such as Courses API or Institutions API) will probably be available even before EWP is "switched on" (although the exact behavior depends on @Awerin's implementation, so I'm not sure).

We can postpone adding the `<include>` for now, but I expect this topic to resurface in a couple of months.

**Comment by wrygiel** [comment]
Related to: https://github.com/erasmus-without-paper/ewp-specs-api-echo/issues/3

If we pick A3 architecture, then each HEI will have its own separate API coverage.

**Comment by wrygiel** [comment]
Resolved in 58930bc35856abd1c527fc0243bdc4ff354ec425 (currently part of `draft-v5` branch, not yet merged to stable).

**Comment by wrygiel** [comment]
@erasmus-without-paper/all-members, you can review the changes [here](https://github.com/erasmus-without-paper/ewp-specs-api-discovery/compare/v4.1.1...v5.0.0-rc1). The DEV Registry Service is already accepting Manifests in v5 format, so we encourage you to test it (especially SOP).

**Comment by wrygiel** [comment]
A month passed, but none of the partners have tested this. I'm not sure if I can release it as stable.

**Comment by georgschermann** [comment]
I hope to find the time to merge our manifests into one and test this next week.
